notifications:
  disabled: true
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby
  - ree
gemfile:
  - Gemfile
  - gemfiles/ruby187.gemfile
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/ruby187.gemfile
    - rvm: 1.9.2
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: ree
      gemfile: gemfiles/ruby187.gemfile
